 name: CI/CD

 on:
  push:
   branches: ["main"]
  workflow_dispatch:

 jobs:
   CI:
      runs-on: ubuntu-latest
      steps: 
      - name: efetuar login no docker hub  
        run: echo "executar login"
      - name: Docker Login   
        uses: docker/login-action@v3.0.0
        with:    
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Build and push Docker images  
        uses: docker/build-push-action@v5.0.0
        with:
         context: ./kube-news/src
         file: src/kube-news/Dockerfile
         push: true
         tags: |
          mateussouzaa/kube-news:${{ github.run_number }}
          mateussouzaa/kube-news:latest
   CD:
    runs-on: ubunto-latest
    needs: CI
    steps:
    - name: autentica na aws
      run: echo "autenticar"
