name: CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubunto-latest
    steps: 
     - name: Docker Login
       run: echo "executar login"
       with:    
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}

     -  name: efetuar o login no docker hub
        run: echo "executar o docker login"
     -  name: enviar a imagem par ao docker registry
        run: echo "executar o docker push"
  CD:
    runs-on: ubunto-latest
    steps:
    needs: [CI]
      
