 name: CI/CD

 on:
  push:
   branches: ["main"]
  workflow_dispatch:

 jobs:
   CI:
      runs-on: ubuntu-latest
      steps: 
      - name: efetuar login no docker hub  
        run: echo "executar login"
      - name: Docker Login   
        uses: docker/login-action@v3.0.0
        with:    
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: efetuar o login no docker hub
        run: echo "executar o docker login"
      - name: enviar a imagem par ao docker registry
        run: echo "executar o docker push"
   CD:
    runs-on: ubunto-latest
    needs: CI
    steps:
    - name: autentica na aws
      run: echo "autenticar"
